apiVersion: v1 
kind: ReplicaSet
metadata: 
  name: demo-app 
spec: 
  replicas: 1
  template: 
    metadata: 
      labels:
        app: demo-app

  spec: 
    containers: 
    - name: demo-app
      image: nginx 

apiversion: v2
kind: Vishnu
